export const modeOfPractices = [
  "General Practitioner (GP)",
  "Specialist Physician",
  "Surgeon",
  "Pediatrician",
  "Obstetrician/Gynecologist (OB/GYN)",
  "Dermatologist",
  "Ophthalmologist",
  "Dentist",
  "Psychiatrist",
  "Anesthesiologist",
  "Radiologist",
  "Pathologist",
  "Emergency Medicine Physician",
  "Oncologist",
  "Rheumatologist",
  "Neurologist",
  "Nephrologist",
  "Cardiologist",
  "Pulmonologist",
  "Geriatrician",
];

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Lakshadweep",
  "Delhi (National Capital Territory of Delhi)",
  "Puducherry",
];

export const doctorDepartments = [
  "Internal Medicine",
  "Surgery",
  "Pediatrics",
  "Obstetrics and Gynecology",
  "Dermatology",
  "Ophthalmology",
  "Dentistry",
  "Psychiatry",
  "Anesthesiology",
  "Radiology",
  "Pathology",
  "Emergency Medicine",
  "Oncology",
  "Rheumatology",
  "Neurology",
  "Nephrology",
  "Cardiology",
  "Pulmonology",
  "Geriatrics",
];
